// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart' show dotenv;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // NOTE: This file reads values from environment variables. Make sure to
  // call `await dotenv.load(fileName: 'assets/.env');` in `main()` before
  // calling `Firebase.initializeApp(...)`.
  //
  // All listed environment variables are required. If a key is missing the
  // app will throw a clear error at startup to prevent using incorrect
  // configuration.

  static String _requiredEnv(String key) => dotenv.env[key] ?? (throw StateError('Missing required environment variable: $key'));
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

    static FirebaseOptions get web => FirebaseOptions(
      apiKey: _requiredEnv('FIREBASE_WEB_API_KEY'),
      appId: _requiredEnv('FIREBASE_WEB_APP_ID'),
      messagingSenderId: _requiredEnv('FIREBASE_WEB_MESSAGING_SENDER_ID'),
      projectId: _requiredEnv('FIREBASE_WEB_PROJECT_ID'),
      authDomain: _requiredEnv('FIREBASE_WEB_AUTH_DOMAIN'),
      storageBucket: _requiredEnv('FIREBASE_WEB_STORAGE_BUCKET'));

    static FirebaseOptions get android => FirebaseOptions(
      apiKey: _requiredEnv('FIREBASE_ANDROID_API_KEY'),
      appId: _requiredEnv('FIREBASE_ANDROID_APP_ID'),
      messagingSenderId: _requiredEnv('FIREBASE_ANDROID_MESSAGING_SENDER_ID'),
      projectId: _requiredEnv('FIREBASE_ANDROID_PROJECT_ID'),
      storageBucket: _requiredEnv('FIREBASE_ANDROID_STORAGE_BUCKET'));

    static FirebaseOptions get ios => FirebaseOptions(
      apiKey: _requiredEnv('FIREBASE_IOS_API_KEY'),
      appId: _requiredEnv('FIREBASE_IOS_APP_ID'),
      messagingSenderId: _requiredEnv('FIREBASE_IOS_MESSAGING_SENDER_ID'),
      projectId: _requiredEnv('FIREBASE_IOS_PROJECT_ID'),
      storageBucket: _requiredEnv('FIREBASE_IOS_STORAGE_BUCKET'),
      iosBundleId: _requiredEnv('FIREBASE_IOS_BUNDLE_ID'));

    static FirebaseOptions get macos => FirebaseOptions(
      apiKey: _requiredEnv('FIREBASE_MACOS_API_KEY'),
      appId: _requiredEnv('FIREBASE_MACOS_APP_ID'),
      messagingSenderId: _requiredEnv('FIREBASE_MACOS_MESSAGING_SENDER_ID'),
      projectId: _requiredEnv('FIREBASE_MACOS_PROJECT_ID'),
      storageBucket: _requiredEnv('FIREBASE_MACOS_STORAGE_BUCKET'),
      iosBundleId: _requiredEnv('FIREBASE_MACOS_BUNDLE_ID'));

    static FirebaseOptions get windows => FirebaseOptions(
      apiKey: _requiredEnv('FIREBASE_WINDOWS_API_KEY'),
      appId: _requiredEnv('FIREBASE_WINDOWS_APP_ID'),
      messagingSenderId: _requiredEnv('FIREBASE_WINDOWS_MESSAGING_SENDER_ID'),
      projectId: _requiredEnv('FIREBASE_WINDOWS_PROJECT_ID'),
      authDomain: _requiredEnv('FIREBASE_WINDOWS_AUTH_DOMAIN'),
      storageBucket: _requiredEnv('FIREBASE_WINDOWS_STORAGE_BUCKET'));
}
